repos:
  
  # Python Linters:

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      -  id: isort

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.0
    hooks:
    -   id: pyupgrade
        args: ['--py37-plus']

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black-jupyter
        language_version: python3

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        language_version: python3
        args:
          - "--max-line-length=99"
          # Allow for lambda functions, line break before binary op, trailing whitespace:
          - "--ignore=E731, W503, W291"