ny_taxi:
  outputs:
    dev:
      dataset: taxi_data
      job_execution_timeout_seconds: 100
      job_retries: 1
      keyfile: "{{ env_var('GCP_KEY_PATH') }}"
      location: australia-southeast1
      method: service-account
      priority: interactive
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      threads: 4
      type: bigquery
  target: dev